pipeline:

 build:
    image: registry.ispacesys.cn/cig/gulp:8.11.1-alpine
    volumes:
      - /cache/yarn:/user/local/share/.cache/yarn/v1
    commands:
      - yarn config set registry https://registry.npm.taobao.org
      - yarn config set @cig:registry https://r.ispacesys.cn
      - yarn install --production

branches: [ dev ]