pipeline:

  # region 构建
  read-cache:
    image: registry.ispacesys.cn/public/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /cache:/cache

branches: [ dev ]