clone:
  git:
    image: registry.ispacesys.cn/public/drone-git:1.4.0

pipeline:

  # region 构建
  read-cache:
    image: registry.ispacesys.cn/public/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /cache:/cache
  # deploy-test:
  #   image: registry.ispacesys.cn/devops/kubernetes:1.0
  #   namespace: test-zhzl
  #   deployment: cigjoin
  #   container: cigjoin
  #   registry: registry.ispacesys.cn
  #   secrets:
  #     - source: kubernetes_server_test
  #       target: kubernetes_server    
  #     - source: kubernetes_cert_test
  #       target: kubernetes_cert    
  #     - source: kubernetes_token_test
  #       target: kubernetes_token               

branches: [ dev ]


# pipeline:
#   build:
#     image: 1794423668/testnode
#     commands:
#       - yarn config set registry https://registry.npm.taobao.org
#       - yarn install --production

#   publish:
#       image: plugins/docker
#       registry: https://index.docker.io/v1/ # 仓库
#       repo: 1794423668/testnode # docker仓库地址
#       # mirror: https://docker.mirrors.ustc.edu.cn
#       # 需要使用drone cli添加secrets: http://docs.drone.io/manage-secrets/
#       secrets: [ 1794423668, docker@123 ]
#       tags:
#         - latest

  # deploy:
  #     image: appleboy/drone-ssh
  #     host: 47.94.204.137
  #     username: root
  #     port: 22
  #     secrets: [ ssh_key ]
  #     script:
  #       - cd /root/app
  #       - docker-compose pull bysir/golang_base
  #       - docker-compose up
